/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedDeviceRouteImport } from './routes/_authed/device'
import { Route as AuthedPlanningRouteImport } from './routes/_authed/planning'
import { Route as AuthedPrintRouteImport } from './routes/_authed/print'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedWorksheetRouteImport } from './routes/_authed/worksheet'
import { Route as AuthedKidIndexRouteImport } from './routes/_authed/kid/index'
import { Route as AuthedKidChildIdRouteImport } from './routes/_authed/kid/$childId'
import { Route as AuthedLessonConversationIdRouteImport } from './routes/_authed/lesson/$conversationId'
import { Route as AuthedPlanningIndexRouteImport } from './routes/_authed/planning/index'
import { Route as AuthedPlanningLibraryRouteImport } from './routes/_authed/planning/library'
import { Route as AuthedPlanningRoutinesRouteImport } from './routes/_authed/planning/routines'
import { Route as AuthedPlanningUnitsRouteImport } from './routes/_authed/planning/units'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDeviceRoute = AuthedDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlanningRoute = AuthedPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPrintRoute = AuthedPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorksheetRoute = AuthedWorksheetRouteImport.update({
  id: '/worksheet',
  path: '/worksheet',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedKidIndexRoute = AuthedKidIndexRouteImport.update({
  id: '/kid/',
  path: '/kid/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedKidChildIdRoute = AuthedKidChildIdRouteImport.update({
  id: '/kid/$childId',
  path: '/kid/$childId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLessonConversationIdRoute =
  AuthedLessonConversationIdRouteImport.update({
    id: '/lesson/$conversationId',
    path: '/lesson/$conversationId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPlanningIndexRoute = AuthedPlanningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPlanningRoute,
} as any)
const AuthedPlanningLibraryRoute = AuthedPlanningLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthedPlanningRoute,
} as any)
const AuthedPlanningRoutinesRoute = AuthedPlanningRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AuthedPlanningRoute,
} as any)
const AuthedPlanningUnitsRoute = AuthedPlanningUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthedPlanningRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/device': typeof AuthedDeviceRoute
  '/planning': typeof AuthedPlanningRouteWithChildren
  '/print': typeof AuthedPrintRoute
  '/settings': typeof AuthedSettingsRoute
  '/worksheet': typeof AuthedWorksheetRoute
  '/kid/$childId': typeof AuthedKidChildIdRoute
  '/lesson/$conversationId': typeof AuthedLessonConversationIdRoute
  '/planning/library': typeof AuthedPlanningLibraryRoute
  '/planning/routines': typeof AuthedPlanningRoutinesRoute
  '/planning/units': typeof AuthedPlanningUnitsRoute
  '/kid/': typeof AuthedKidIndexRoute
  '/planning/': typeof AuthedPlanningIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/device': typeof AuthedDeviceRoute
  '/print': typeof AuthedPrintRoute
  '/settings': typeof AuthedSettingsRoute
  '/worksheet': typeof AuthedWorksheetRoute
  '/': typeof AuthedIndexRoute
  '/kid/$childId': typeof AuthedKidChildIdRoute
  '/lesson/$conversationId': typeof AuthedLessonConversationIdRoute
  '/planning/library': typeof AuthedPlanningLibraryRoute
  '/planning/routines': typeof AuthedPlanningRoutinesRoute
  '/planning/units': typeof AuthedPlanningUnitsRoute
  '/kid': typeof AuthedKidIndexRoute
  '/planning': typeof AuthedPlanningIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/device': typeof AuthedDeviceRoute
  '/_authed/planning': typeof AuthedPlanningRouteWithChildren
  '/_authed/print': typeof AuthedPrintRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/worksheet': typeof AuthedWorksheetRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/kid/$childId': typeof AuthedKidChildIdRoute
  '/_authed/lesson/$conversationId': typeof AuthedLessonConversationIdRoute
  '/_authed/planning/library': typeof AuthedPlanningLibraryRoute
  '/_authed/planning/routines': typeof AuthedPlanningRoutinesRoute
  '/_authed/planning/units': typeof AuthedPlanningUnitsRoute
  '/_authed/kid/': typeof AuthedKidIndexRoute
  '/_authed/planning/': typeof AuthedPlanningIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/device'
    | '/planning'
    | '/print'
    | '/settings'
    | '/worksheet'
    | '/kid/$childId'
    | '/lesson/$conversationId'
    | '/planning/library'
    | '/planning/routines'
    | '/planning/units'
    | '/kid/'
    | '/planning/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/logout'
    | '/signup'
    | '/device'
    | '/print'
    | '/settings'
    | '/worksheet'
    | '/'
    | '/kid/$childId'
    | '/lesson/$conversationId'
    | '/planning/library'
    | '/planning/routines'
    | '/planning/units'
    | '/kid'
    | '/planning'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/device'
    | '/_authed/planning'
    | '/_authed/print'
    | '/_authed/settings'
    | '/_authed/worksheet'
    | '/_authed/'
    | '/_authed/kid/$childId'
    | '/_authed/lesson/$conversationId'
    | '/_authed/planning/library'
    | '/_authed/planning/routines'
    | '/_authed/planning/units'
    | '/_authed/kid/'
    | '/_authed/planning/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/device': {
      id: '/_authed/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof AuthedDeviceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/planning': {
      id: '/_authed/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AuthedPlanningRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/print': {
      id: '/_authed/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof AuthedPrintRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/worksheet': {
      id: '/_authed/worksheet'
      path: '/worksheet'
      fullPath: '/worksheet'
      preLoaderRoute: typeof AuthedWorksheetRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/kid/': {
      id: '/_authed/kid/'
      path: '/kid'
      fullPath: '/kid/'
      preLoaderRoute: typeof AuthedKidIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/kid/$childId': {
      id: '/_authed/kid/$childId'
      path: '/kid/$childId'
      fullPath: '/kid/$childId'
      preLoaderRoute: typeof AuthedKidChildIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/lesson/$conversationId': {
      id: '/_authed/lesson/$conversationId'
      path: '/lesson/$conversationId'
      fullPath: '/lesson/$conversationId'
      preLoaderRoute: typeof AuthedLessonConversationIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/planning/': {
      id: '/_authed/planning/'
      path: '/'
      fullPath: '/planning/'
      preLoaderRoute: typeof AuthedPlanningIndexRouteImport
      parentRoute: typeof AuthedPlanningRoute
    }
    '/_authed/planning/library': {
      id: '/_authed/planning/library'
      path: '/library'
      fullPath: '/planning/library'
      preLoaderRoute: typeof AuthedPlanningLibraryRouteImport
      parentRoute: typeof AuthedPlanningRoute
    }
    '/_authed/planning/routines': {
      id: '/_authed/planning/routines'
      path: '/routines'
      fullPath: '/planning/routines'
      preLoaderRoute: typeof AuthedPlanningRoutinesRouteImport
      parentRoute: typeof AuthedPlanningRoute
    }
    '/_authed/planning/units': {
      id: '/_authed/planning/units'
      path: '/units'
      fullPath: '/planning/units'
      preLoaderRoute: typeof AuthedPlanningUnitsRouteImport
      parentRoute: typeof AuthedPlanningRoute
    }
  }
}

interface AuthedPlanningRouteChildren {
  AuthedPlanningLibraryRoute: typeof AuthedPlanningLibraryRoute
  AuthedPlanningRoutinesRoute: typeof AuthedPlanningRoutinesRoute
  AuthedPlanningUnitsRoute: typeof AuthedPlanningUnitsRoute
  AuthedPlanningIndexRoute: typeof AuthedPlanningIndexRoute
}

const AuthedPlanningRouteChildren: AuthedPlanningRouteChildren = {
  AuthedPlanningLibraryRoute: AuthedPlanningLibraryRoute,
  AuthedPlanningRoutinesRoute: AuthedPlanningRoutinesRoute,
  AuthedPlanningUnitsRoute: AuthedPlanningUnitsRoute,
  AuthedPlanningIndexRoute: AuthedPlanningIndexRoute,
}

const AuthedPlanningRouteWithChildren = AuthedPlanningRoute._addFileChildren(
  AuthedPlanningRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDeviceRoute: typeof AuthedDeviceRoute
  AuthedPlanningRoute: typeof AuthedPlanningRouteWithChildren
  AuthedPrintRoute: typeof AuthedPrintRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedWorksheetRoute: typeof AuthedWorksheetRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedKidChildIdRoute: typeof AuthedKidChildIdRoute
  AuthedLessonConversationIdRoute: typeof AuthedLessonConversationIdRoute
  AuthedKidIndexRoute: typeof AuthedKidIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDeviceRoute: AuthedDeviceRoute,
  AuthedPlanningRoute: AuthedPlanningRouteWithChildren,
  AuthedPrintRoute: AuthedPrintRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedWorksheetRoute: AuthedWorksheetRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedKidChildIdRoute: AuthedKidChildIdRoute,
  AuthedLessonConversationIdRoute: AuthedLessonConversationIdRoute,
  AuthedKidIndexRoute: AuthedKidIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
